// import Story from "../classes/Story";
import Chapter from "../classes/Chapter";
import Baddie from "../classes/Baddie";
import Shop from "../classes/Shop";
import Adventure from "../classes/Adventure";
import Item from "../classes/Item";
import Pog from "../classes/Pog";
import Slammer from "../classes/Slammer";
import Floor from "../classes/Floor";
import Story from "../classes/Story";

import demoSlammerAbility2 from "../slammerResources/demoSlammerAbility2";
import demoSlammerAbilityByN from "../slammerResources/demoSlammerAbilityByN";

function createDemoStory() {
    return new Story(
        "Demo Story",
        "This is a demo story.",
        [ new Floor("First Floor", "First Floor Description", [
            new Chapter("The beginning", ["This is a demo description 1.", "This is a demo description 2.", "This is a demo description 3."], 
                new Baddie("Baddie 1", 
                    [new Pog("Butt Pog 1", 1, 1, 1, 1), 
                        new Pog("Butt Pog 2", 1, 1, 1, 1), 
                        new Pog("Butt Pog 3", 1, 1, 1, 1)], 
                        100, 1)),
                new Chapter("The monster breaths", ["This is a demo description 1.", "This is a demo description 2.", "This is a demo description 3."], 
                    new Baddie("Baddie 1", 
                        [new Pog("Butt Pog 1", 1, 1, 1, 1), 
                            new Pog("Butt Pog 2", 1, 2, 1, 1), 
                            new Pog("Butt Pog 2", 3, 1, 1, 1), 
                            new Pog("Butt Pog 2", 3, 1, 1, 1), 
                            new Pog("Butt Pog 3", 1, 1, 1, 1)], 
                            100, 1)),
            new Chapter("The middle", ["This is a demo description 4.", "This is a demo description 5.", "This is a demo description 6."], 
                new Shop("Shop 1", "This is a demo shop.", 
                    [new Item("Item 1", "This is a demo item.", 1), 
                    new Item("Item 2", "This is a demo item.", 2)], 
                    [new Pog("Big Pog City", 10, 1, 50, 1),
                        new Pog("Big Honker", 10, 10, 250, 1),
                    new Pog("Biiig Defense", 2, 10, 20, 1),], 
                    [new Slammer("Slammer 2", "This is a second level slammer.", 1, 10, demoSlammerAbility2)])),
            new Chapter("The end", ["This is a demo description 7.", "This is a demo description 8.", "This is a demo description 9."], 
                new Adventure("Adventure 1", "This is a demo description.", "trade")),
            new Chapter("The end", ["This is a demo description 7.", "This is a demo description 8.", "This is a demo description 9."], 
                new Adventure("Adventure 1", "This is a demo description.", "campfire")),

            new Chapter("The beginning again", ["This is a demo description 10.", "This is a demo description 11.", "This is a demo description 12."], 
                new Baddie("Baddie 2", 
                    [new Pog("Butt Pog 1", 1, 1, 1, 1), 
                        new Pog("Butt Pog 2", 1, 1, 1, 1), 
                        new Pog("Butt Pog 4", 1, 1, 1, 1),
                        new Pog("Butt Pog 5", 1, 1, 1, 1),
                        new Pog("Butt Pog 6", 1, 1, 1, 1),
                        new Pog("Butt Pog 7", 1, 1, 1, 1),
                        new Pog("Butt Pog 3", 1, 1, 1, 1)], 100, 2)),
            new Chapter("The beginning again", ["This is a demo description 10.", "This is a demo description 11.", "This is a demo description 12."], 
                new Baddie("Baddie 2", 
                    [new Pog("Butt Pog 1", 2, 2, 1, 1), 
                        new Pog("Butt Pog 2", 4, 4, 1, 1), 
                        new Pog("Butt Pog 4", 4, 4, 1, 1),
                        new Pog("Butt Pog 2", 4, 4, 1, 1), 
                        new Pog("Butt Pog 4", 4, 4, 1, 1),
                        new Pog("Butt Pog 2", 4, 4, 1, 1), 
                        new Pog("Butt Pog 4", 4, 4, 1, 1),
                        new Pog("Butt Pog 5", 1, 1, 1, 1),
                        new Pog("Butt Pog 6", 1, 1, 1, 1),
                        new Pog("Butt Pog 7", 1, 1, 1, 1),
                        new Pog("Butt Pog 3", 1, 1, 1, 1)], 100, 2)),
            new Chapter("The middle again", ["This is a demo description 13.", "This is a demo description 14.", "This is a demo description 15."], 
                new Shop("Shop 1", "This is a demo shop.", 
                    [new Item("Item 1", "This is a demo item.", 1)], 
                    [new Pog("Pog 1", 1, 1, 1, 1),
                        new Pog("The funky chicken", 10, 10, 250, 1),
                        new Pog("Banana Sam", 7, 7, 25, 1),
                    ], 
                    [new Slammer("Slammer 4", "This is a level 4 demo slammer.", 1, 25, 
                        demoSlammerAbilityByN(3))])),
            new Chapter("The end again", ["This is a demo description 16.", "This is a demo description 17.", "This is a demo description 18."], 
                new Adventure("Adventure 1", "This is a demo description.", "chase")),
            new Chapter("The beginning again", ["This is a demo description 19.", "This is a demo description 20.", "This is a demo description 21."], 
                new Baddie("Baddie 3", 
                    [new Pog("Butt Pog 1", 1, 1, 1, 1), 
                        new Pog("Butt Pog 2", 1, 1, 1, 1), 
                        new Pog("Big Honker", 10, 10, 250, 1),
                        new Pog("Biiig Defense", 2, 10, 20, 1), 
                        new Pog("Big Honker", 10, 10, 250, 1),
                        new Pog("Biiig Defense", 2, 10, 20, 1), 
                        new Pog("Big Honker", 10, 10, 250, 1),
                        new Pog("Biiig Defense", 2, 10, 20, 1), 
                        new Pog("Big Honker", 10, 10, 250, 1),
                        new Pog("Butt Pog 3", 1, 1, 1, 1)], 100, 3)),
            new Chapter("The middle again", ["This is a demo description 22.", "This is a demo description 23.", "This is a demo description 24."], 
                new Shop("Shop 1", "This is a demo shop.", 
                    [new Item("Item 1", "This is a demo item.", 1)], 
            [new Pog("Butt Pog 1", 1, 1, 1, 1),
                new Pog("Tale of Jonny Pizza", 5, 3, 35, 1),
                new Pog("Welcome to Space", 2, 5, 12, 1),
                new Pog("Gumby", 3, 3, 10, 1),
                new Pog("Super Mario Bros", 4, 4, 15, 1),
                new Pog("The Legend of Zelda", 5, 5, 20, 1),
                new Pog("Pac-Man", 6, 6, 25, 1),
                new Pog("Donkey Kong", 7, 7, 30, 1),
                new Pog("Mario Kart", 8, 8, 35, 1),
                new Pog("Super Mario Bros 3", 9, 9, 40, 1),
                new Pog("The Legend of Zelda 2", 10, 10, 45, 1),
                new Pog("Pac-Man 2", 11, 11, 50, 1),
                new Pog("Donkey Kong 2", 12, 12, 55, 1),
                new Pog("Mario Kart 2", 13, 13, 60, 1),
                new Pog("Super Mario Bros 3 2", 14, 14, 65, 1),
                new Pog("The Legend of Zelda 3", 15, 15, 70, 1),
                new Pog("Pac-Man 3", 16, 16, 75, 1),
                new Pog("Donkey Kong 3", 17, 17, 80, 1),
            ], 
            [new Slammer("Slammer 7", "This is a level 7 demo slammer.", 1, 50, demoSlammerAbilityByN(4))])),
            new Chapter("The end again", ["This is a demo description 25.", "This is a demo description 26.", "This is a demo description 27."], 
                new Adventure("Adventure 1", "This is a demo description.", "chest")),
            ]),
        new Floor("Second Floor", "Second Floor Description", [
            new Chapter("The beginning", ["This is a demo description 28.", "This is a demo description 29.", "This is a demo description 30."], 
                new Baddie("Baddie 4", 
                    [new Pog("Butt Pog 1", 1, 1, 1, 1), 
                        new Pog("Butt Pog 2", 1, 1, 1, 1),
                        new Pog("Big Honker", 10, 10, 250, 1),
                        new Pog("Tale of Jonny Pizza", 5, 3, 35, 1),
                        new Pog("Welcome to Space", 2, 5, 12, 1),
                        new Pog("Gumby", 3, 3, 10, 1),
                        new Pog("Super Mario Bros", 4, 4, 15, 1),
                        new Pog("The Legend of Zelda", 5, 5, 20, 1),
                        new Pog("Pac-Man", 6, 6, 25, 1),
                        new Pog("Donkey Kong", 7, 7, 30, 1),
                        new Pog("Mario Kart", 8, 8, 35, 1),
                        new Pog("Biiig Defense", 2, 10, 20, 1), 
                        new Pog("Butt Pog 3", 1, 1, 1, 1)], 100, 4)),
            new Chapter("The middle", ["This is a demo description 31.", "This is a demo description 32.", "This is a demo description 33."], 
                new Shop("Shop 1", "This is a demo shop.", 
                    [new Item("Item 1", "This is a demo item.", 1)], 
                    [new Pog("Pog 1", 1, 1, 1, 1),
                        new Pog("Big Honker", 10, 10, 250, 1),
                        new Pog("Pog Mania", 20, 20, 100, 1),
                        new Pog("Biiig Defense", 2, 10, 20, 1),
                    ], 
                    [new Slammer("Slammer 125", "This is a level 125 demo slammer.", 1, 75, demoSlammerAbilityByN(6))])),
            new Chapter("The end", ["This is a demo description 34.", "This is a demo description 35.", "This is a demo description 36."], 
                new Adventure("Adventure 1", "This is a demo description.", "trade")),
            new Chapter("Just kidding the REAL end", ["This is a demo description 37.", "This is a demo description 38.", "This is a demo description 39."], 
                new Baddie("Baddie 5", 
                    [new Pog("Butt Pog 1", 1, 1, 1, 1), 
                        new Pog("Butt Pog 2", 3, 1, 1, 1),
                        new Pog("Butt Pog 4", 3, 3, 1, 1),
                        new Pog("Butt Pog 5", 4, 4, 1, 1),
                        new Pog("Butt Pog 6", 4, 4, 1, 1),
                        new Pog("Butt Pog 7", 4, 4, 1, 1),
                        new Pog("Butt Pog 8", 4, 4, 1, 1),
                        new Pog("Butt Pog 9", 4, 4, 1, 1),
                        new Pog("Butt Pog 10", 4, 4, 1, 1),
                        new Pog("Butt Pog 11", 4, 4, 1, 1),
                        new Pog("Butt Pog 12", 4, 4, 1, 1),
                        new Pog("Butt Pog 13", 4, 4, 1, 1),
                        new Pog("Butt Pog 14", 4, 4, 1, 1),
                        new Pog("Butt Pog 15", 4, 4, 1, 1),
                        new Pog("Butt Pog 16", 4, 4, 1, 1),
                        new Pog("Butt Pog 17", 4, 4, 1, 1),
                        new Pog("Butt Pog 18", 4, 4, 1, 1),
                        new Pog("Butt Pog 19", 4, 4, 1, 1),
                        new Pog("Butt Pog 20", 4, 4, 1, 1),
                        new Pog("Butt Pog 21", 4, 4, 1, 1),
                        new Pog("Butt Pog 22", 4, 4, 1, 1),
                        new Pog("Butt Pog 23", 4, 4, 1, 1),
                        new Pog("Butt Pog 24", 4, 4, 1, 1),
                        new Pog("Butt Pog 25", 4, 4, 1, 1),
                        new Pog("Butt Pog 26", 4, 4, 1, 1),
                        new Pog("Butt Pog 27", 4, 4, 1, 1),
                        new Pog("Butt Pog 28", 4, 4, 1, 1),
                        new Pog("Butt Pog 3", 10, 10, 1, 1)], 100, 10),)    
        ])
    ]);
}


export default createDemoStory;